[build]
  # This will be run the site build
  command = "npm run build:functions"
  commandOrigin = "config"
  environment = - ACCESS_TOKEN
  # This is the directory is publishing to netlify's CDN
  # and this is directory of your front of your app
  publish = "/opt/build/repo"
  publishOrigin = "ui"
  # functions build directory
  functions = "functions-build" # always appends `-build` folder to your `functions` folder for builds